services:
  - type: web
    name: laravel-app
    runtime: docker
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: tu-host-de-render
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: tu-base-de-datos
      - key: DB_USERNAME
        value: tu-usuario
      - key: DB_PASSWORD
        value: tu-contraseña
